import { BREAK_POINTS_METRIC, BREAK_POINTS_SIZE } from '../types/breakpoints'

const breakpoints: Record<BREAK_POINTS_SIZE, BREAK_POINTS_METRIC> = {
    [BREAK_POINTS_SIZE.SMALL]: BREAK_POINTS_METRIC.SMALL,
    [BREAK_POINTS_SIZE.MEDIUM]: BREAK_POINTS_METRIC.MEDIUM,
    [BREAK_POINTS_SIZE.LARGE]: BREAK_POINTS_METRIC.LARGE,
    [BREAK_POINTS_SIZE.XLARGE]: BREAK_POINTS_METRIC.XLARGE,
}

export default breakpoints
